services:
  - type: web
    name: learntech
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PESAPAL_CONSUMER_KEY
        sync: false
      - key: PESAPAL_CONSUMER_SECRET
        sync: false
      - key: PESAPAL_BASE_URL
        value: https://cybqa.pesapal.com/pesapalv3
      - key: PESAPAL_CALLBACK_URL
        value: https://learntech-lvem.onrender.com/pesapal/callback
